### ISSUE TITLE
handle.stl and large_handle.stl both contain other parts

### ISSUE THREAD

**Issue by Billfred** [makersmakingchange/Universal-Lockable-Joint#1]
https://github.com/makersmakingchange/Universal-Lockable-Joint/blob/main/3D%20Print%20Files/handle.STL and https://github.com/makersmakingchange/Universal-Lockable-Joint/blob/main/3D%20Print%20Files/large_handle.STL both appear to contain exports of _all_ the parts for this joint, not just the handles.  

Which makes it challenging to make everything fit neatly on the print bed. 😅

**Comment by jakemcivor** [comment]
Thanks - this was probably a result of me trying to correct the print orientations in the STLs.
